#!/usr/bin/env python3
"""Run CUDA MTP proof-bar comparisons across prompt and flag variants.

This is an integration harness for GB10/DGX Spark style runs.  It compares
generated bytes from no-MTP, current optimized MTP, rollback variants, strict
mode, and optional shadow diagnostics.  Model paths are intentionally supplied
by flags or environment variables so the script can run on either the local
tree or a LAN Spark checkout.
"""

from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path


DEFAULT_PROOF_PROMPTS = [
    "List 100 prime numbers, comma-separated, just numbers.",
    "Write a concise explanation of how speculative decoding works, then give three caveats.",
    "Write a short C function that returns the maximum value in an int array.",
    "Summarize why GPU kernel launch overhead matters for small decode batches.",
    "Give eight terse bullet points about deterministic testing for inference engines.",
    "Continue this sequence with one item per line: alpha, beta, gamma, delta.",
    "Explain the tradeoff between exact speculative decoding and approximate draft acceptance.",
    "Write a compact JSON object with keys name, purpose, risks, and validation.",
]

DEFAULT_PROMPTS = DEFAULT_PROOF_PROMPTS[:2]


@dataclass(frozen=True)
class BudgetPreset:
    name: str
    tokens: int
    prompt_count: int


BUDGET_PRESETS = {
    "smoke": BudgetPreset("smoke", tokens=64, prompt_count=2),
    "candidate": BudgetPreset("candidate", tokens=512, prompt_count=4),
    "default-on": BudgetPreset("default-on", tokens=1024, prompt_count=8),
    "nightly": BudgetPreset("nightly", tokens=2048, prompt_count=8),
}


@dataclass(frozen=True)
class Variant:
    name: str
    env: dict[str, str]
    use_mtp: bool = True


VARIANTS = [
    Variant("mtp-fast", {
        "DS4_CUDA_MTP_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_OPT_OUTPUT": "1",
    }),
    Variant("mtp-fast-shadow-b", {
        "DS4_CUDA_MTP_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_OPT_OUTPUT": "1",
        "DS4_CUDA_MTP_SHADOW_B_N2_Q8": "1",
        "DS4_MTP_TIMING": "1",
    }),
    Variant("mtp-no-opt-output", {
        "DS4_CUDA_MTP_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_TOP2": "1",
    }),
    Variant("mtp-no-verify-top2", {
        "DS4_CUDA_MTP_TOP2": "1",
    }),
    Variant("mtp-rollback-structural", {
        "DS4_CUDA_MTP_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_OPT_OUTPUT": "1",
        "DS4_CUDA_NO_BATCH_Q8_PAIR": "1",
        "DS4_CUDA_MOE_NO_DIRECT_DOWN_SUM6_N2": "1",
        "DS4_CUDA_NO_DECODE_Q8_PAIR": "1",
    }),
    Variant("mtp-exact-replay", {
        "DS4_CUDA_MTP_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_OPT_OUTPUT": "1",
        "DS4_MTP_EXACT_REPLAY": "1",
    }),
    Variant("mtp-strict", {
        "DS4_CUDA_MTP_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_TOP2": "1",
        "DS4_CUDA_MTP_VERIFY_OPT_OUTPUT": "1",
        "DS4_MTP_STRICT": "1",
    }),
]


SHADOW_RE = re.compile(
    r"mtp shadow b_n2_q8 .*?\sagree=(?P<agree>[01]).*?"
    r"\slogit_agree=(?P<logit_agree>[01]).*?"
    r"logit_max_abs=(?P<max_abs>[-+0-9.eE]+).*?"
    r"logit_rms=(?P<rms>[-+0-9.eE]+)"
)


def parse_env_map(spec: str) -> Variant:
    """Parse NAME:KEY=VALUE,KEY2=VALUE2 into a fast-MTP proof variant."""
    if ":" not in spec:
        raise argparse.ArgumentTypeError("custom variant must be NAME:KEY=VALUE,...")
    name, env_spec = spec.split(":", 1)
    name = name.strip()
    if not name:
        raise argparse.ArgumentTypeError("custom variant name is empty")
    env: dict[str, str] = {}
    for item in re.split(r"[,;]", env_spec):
        item = item.strip()
        if not item:
            continue
        if "=" not in item:
            raise argparse.ArgumentTypeError(f"custom env item lacks '=': {item!r}")
        key, value = item.split("=", 1)
        key = key.strip()
        if not key:
            raise argparse.ArgumentTypeError("custom env key is empty")
        env[key] = value
    if not env:
        raise argparse.ArgumentTypeError("custom variant has no environment flags")
    return Variant(name, env)


def first_diff(a: bytes, b: bytes) -> int | None:
    n = min(len(a), len(b))
    for i in range(n):
        if a[i] != b[i]:
            return i
    if len(a) != len(b):
        return n
    return None


def snippet(data: bytes, pos: int | None, width: int = 80) -> str:
    if pos is None:
        return ""
    start = max(0, pos - width // 2)
    end = min(len(data), pos + width // 2)
    return data[start:end].decode("utf-8", errors="replace").replace("\n", "\\n")


def run_case(
    *,
    bin_path: str,
    base_model: str,
    mtp_model: str,
    prompt: str,
    tokens: int,
    variant: Variant,
    out_path: Path,
    log_path: Path,
) -> int:
    env = os.environ.copy()
    env.update(variant.env)
    cmd = [
        bin_path,
        "--cuda",
        "-m",
        base_model,
        "--temp",
        "0",
        "--nothink",
        "-n",
        str(tokens),
        "-p",
        prompt,
    ]
    if variant.use_mtp:
        cmd[4:4] = ["--mtp", mtp_model, "--mtp-draft", "2"]
    with out_path.open("wb") as out_f, log_path.open("wb") as log_f:
        proc = subprocess.run(cmd, env=env, stdout=out_f, stderr=log_f)
    return proc.returncode


def parse_shadow(log_text: str) -> tuple[int, int, int, float, float]:
    checks = 0
    decision_disagree = 0
    logit_disagree = 0
    max_abs = 0.0
    max_rms = 0.0
    for m in SHADOW_RE.finditer(log_text):
        checks += 1
        if m.group("agree") != "1":
            decision_disagree += 1
        if m.group("logit_agree") != "1":
            logit_disagree += 1
        max_abs = max(max_abs, float(m.group("max_abs")))
        max_rms = max(max_rms, float(m.group("rms")))
    return checks, decision_disagree, logit_disagree, max_abs, max_rms


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bin", default=os.environ.get("DS4_PROOF_BIN", "./ds4"))
    ap.add_argument("--base", default=os.environ.get("DS4_PROOF_BASE"))
    ap.add_argument("--mtp", default=os.environ.get("DS4_PROOF_MTP"))
    ap.add_argument("--budget", choices=sorted(BUDGET_PRESETS),
                    help="Named proof budget. --tokens overrides the preset token count.")
    ap.add_argument("--tokens", type=int)
    ap.add_argument("--work-dir", default="/tmp/ds4_mtp_proof")
    ap.add_argument("--prompt", action="append", dest="prompts")
    ap.add_argument(
        "--only",
        action="append",
        help="Variant name to run. May be repeated. Defaults to all variants.",
    )
    ap.add_argument(
        "--custom",
        action="append",
        type=parse_env_map,
        default=[],
        metavar="NAME:KEY=VALUE,...",
        help="Add an MTP variant without editing this script.",
    )
    args = ap.parse_args()

    if not args.base or not args.mtp:
        ap.error("provide --base/--mtp or DS4_PROOF_BASE/DS4_PROOF_MTP")

    budget = BUDGET_PRESETS.get(args.budget) if args.budget else None
    tokens = args.tokens
    if tokens is None:
        tokens = budget.tokens if budget else 96
    prompts = args.prompts or DEFAULT_PROOF_PROMPTS[:budget.prompt_count if budget else len(DEFAULT_PROMPTS)]
    custom_variants = [
        Variant(v.name, {**VARIANTS[0].env, **v.env}, use_mtp=v.use_mtp)
        for v in args.custom
    ]
    all_variants = VARIANTS + custom_variants
    selected = set(args.only or [v.name for v in all_variants])
    variants = [v for v in all_variants if v.name in selected]
    unknown = selected - {v.name for v in all_variants}
    if unknown:
        ap.error(f"unknown variants: {', '.join(sorted(unknown))}")

    work = Path(args.work_dir)
    work.mkdir(parents=True, exist_ok=True)

    print(
        f"cuda-mtp-proof variants={len(variants)} prompts={len(prompts)} "
        f"tokens={tokens} budget={args.budget or '-'}"
    )

    failures = 0
    for pi, prompt in enumerate(prompts):
        print(f"\n=== prompt[{pi}] {prompt[:80]!r}")
        nomtp = Variant("nomtp", {}, use_mtp=False)
        base_out = work / f"p{pi:02d}_nomtp.out"
        base_log = work / f"p{pi:02d}_nomtp.log"
        rc = run_case(
            bin_path=args.bin,
            base_model=args.base,
            mtp_model=args.mtp,
            prompt=prompt,
            tokens=tokens,
            variant=nomtp,
            out_path=base_out,
            log_path=base_log,
        )
        if rc != 0:
            print(f"nomtp FAILED rc={rc} log={base_log}")
            return 2
        base_bytes = base_out.read_bytes()

        fast_bytes: bytes | None = None
        for variant in variants:
            out = work / f"p{pi:02d}_{variant.name}.out"
            log = work / f"p{pi:02d}_{variant.name}.log"
            rc = run_case(
                bin_path=args.bin,
                base_model=args.base,
                mtp_model=args.mtp,
                prompt=prompt,
                tokens=tokens,
                variant=variant,
                out_path=out,
                log_path=log,
            )
            if rc != 0:
                print(f"{variant.name:24s} FAILED rc={rc} log={log}")
                failures += 1
                continue
            data = out.read_bytes()
            if variant.name == "mtp-fast":
                fast_bytes = data
            diff_nomtp = first_diff(base_bytes, data)
            nomtp_status = "MATCH" if diff_nomtp is None else f"DIFF@{diff_nomtp}"
            fast_status = "n/a"
            if fast_bytes is not None and variant.name != "mtp-fast":
                diff_fast = first_diff(fast_bytes, data)
                fast_status = "MATCH" if diff_fast is None else f"DIFF@{diff_fast}"
            log_text = log.read_text(errors="replace")
            shadow = parse_shadow(log_text)
            shadow_text = ""
            if shadow[0]:
                shadow_text = (
                    f" shadow checks={shadow[0]} decision_bad={shadow[1]} "
                    f"logit_bad={shadow[2]} max_abs={shadow[3]:.6g} rms={shadow[4]:.6g}"
                )
            print(
                f"{variant.name:24s} vs_nomtp={nomtp_status:12s} "
                f"vs_fast={fast_status:12s} out={out} log={log}{shadow_text}"
            )
            if diff_nomtp is not None:
                print(f"  nomtp: {snippet(base_bytes, diff_nomtp)}")
                print(f"  {variant.name}: {snippet(data, diff_nomtp)}")
                failures += 1
            if shadow[1] or shadow[2]:
                failures += 1

    return 1 if failures else 0


if __name__ == "__main__":
    sys.exit(main())
