// SPDX-License-Identifier: MIT
// Generated by test_gpu_iq2_signs.py with current production helpers inserted.
#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <vector>
#if defined(__HIPCC__)
#include <hip/hip_runtime.h>
#include <hip/hip_fp16.h>
#define GPU(name) hip##name
#define DEVICE __device__
#elif defined(__CUDACC__)
#include <cuda_runtime.h>
#include <cuda_fp16.h>
#define GPU(name) cuda##name
#define DEVICE __device__
#else
#define DEVICE
using __half = _Float16;
static float __half2float(__half v) { return float(v); }
static unsigned __popc(unsigned v) { return __builtin_popcount(v); }
// Exact packed-byte comparison/subtraction and signed DP4A, no saturation.
#ifndef TEST_ROCM_HOST
static int32_t host_vcmpne4(uint32_t a, uint32_t b) {
    uint32_t r = 0;
    for (unsigned i = 0; i < 4; ++i)
        r |= (((a >> (8*i)) & 255) != ((b >> (8*i)) & 255) ? 255u : 0u) << (8*i);
    return int32_t(r);
}
static int32_t host_vsub4(int32_t a, int32_t b) {
    uint32_t r = 0;
    for (unsigned i = 0; i < 4; ++i)
        r |= (((uint32_t(a) >> (8*i)) - (uint32_t(b) >> (8*i))) & 255) << (8*i);
    return int32_t(r);
}
static int32_t host_dp4a(int32_t a, int32_t b, int32_t c) {
    for (unsigned i = 0; i < 4; ++i)
        c += int8_t(uint32_t(a) >> (8*i)) * int8_t(uint32_t(b) >> (8*i));
    return c;
}
#define __vcmpne4 host_vcmpne4
#define __vsub4 host_vsub4
#define __dp4a host_dp4a
#endif
#endif

// PRODUCTION_SOURCE

static_assert(sizeof(cuda_block_iq2_xxs) == 66, "IQ2 block ABI");
static_assert(sizeof(cuda_block_q8_K) == 292, "Q8_K block ABI");
DEVICE static uint32_t bits(float v) {
#ifdef GPU
    return __float_as_uint(v);
#else
    uint32_t u; std::memcpy(&u,&v,sizeof(u)); return u;
#endif
}
DEVICE static uint32_t rng(uint32_t &s) { return s=s*1664525u+1013904223u; }
DEVICE static int weight(unsigned grid, unsigned sign, unsigned i) {
    const int w = int((cuda_iq2xxs_grid[grid] >> (8*i)) & 255);
    return cuda_ksigns_iq2xs[sign] & (1u << i) ? -w : w;
}
DEVICE static int dot(unsigned grid, unsigned sign, const int8_t *a) {
    int r=0; for (unsigned i=0; i<8; ++i) r += weight(grid,sign,i)*a[i]; return r;
}
DEVICE static uint32_t signs_case(unsigned id) {
    const unsigned sign=id/256, grid=id%256;
    if (production::dev_unpack_iq2_signs(sign) != uint32_t(cuda_ksigns_iq2xs[sign])*0x01010101u) return 1;
    int32_t packed[4] = {0x12345678,0,0,0x12345678};
    production::dev_iq2_i8x8_lut(cuda_iq2xxs_grid,uint8_t(grid),sign,&packed[1],&packed[2]);
    if (packed[0]!=0x12345678 || packed[3]!=0x12345678) return 2;
    for (unsigned i=0; i<8; ++i)
        if (int8_t(uint32_t(packed[1+i/4]) >> (8*(i%4))) != weight(grid,sign,i)) return 3;
#ifdef TEST_ROCM
    cuda_block_iq2_xxs block{}; block.d=0x3c00;
    const uint32_t grids=grid*0x01010101u;
    const uint32_t signs=sign | (sign<<7) | (sign<<14) | (sign<<21);
    block.qs[0]=uint16_t(grids); block.qs[1]=uint16_t(grids>>16);
    block.qs[2]=uint16_t(signs); block.qs[3]=uint16_t(signs>>16);
    for (unsigned i=0; i<32; ++i)
        if (bits(production::iq2_xxs_dequant_256_direct(reinterpret_cast<const unsigned char *>(&block),i)) !=
            bits(0.125f*float(weight(grid,sign,i%8)))) return 6;
#endif
    for (unsigned pattern=0; pattern<4; ++pattern) {
        alignas(4) int8_t q[16]; uint32_t state=id*12345u+pattern;
        for (unsigned i=0; i<16; ++i)
            q[i]=pattern==0 ? -128 : pattern==1 ? 127 : pattern==2 ? (i&1 ? -128 : 127) : int8_t(rng(state)>>24);
        if (production::dev_iq2_dp4a_8(cuda_iq2xxs_grid[grid],sign,q,-7919) != dot(grid,sign,q)-7919) return 4;
        if (production::dev_dot_iq2_pair_16(uint8_t(grid),sign,uint8_t(255-grid),127-sign,q) !=
            dot(grid,sign,q)+dot(255-grid,127-sign,q+8)) return 5;
    }
    return 0;
}

DEVICE static int block_sum(const cuda_block_iq2_xxs &x, const cuda_block_q8_K &y) {
    int sum=0;
    for (unsigned b=0; b<8; ++b) {
        const uint32_t g=x.qs[4*b] | (uint32_t(x.qs[4*b+1])<<16);
        const uint32_t s=x.qs[4*b+2] | (uint32_t(x.qs[4*b+3])<<16);
        int part=0;
        for (unsigned i=0; i<32; ++i) part += weight((g>>(8*(i/8)))&255,(s>>(7*(i/8)))&127,i%8)*y.qs[32*b+i];
        sum += part*int(2*(s>>28)+1);
    }
    return sum;
}
DEVICE static uint32_t block_case(unsigned id) {
    cuda_block_iq2_xxs x; cuda_block_q8_K y[8]; uint32_t state=id+0x9751ab21u;
    const uint16_t scales[] = {0,1,0x1000,0x3555,0x3c00,0x7bff};
    x.d=scales[id%6];
    for (unsigned i=0; i<32; ++i) x.qs[i]=uint16_t(rng(state)>>16);
    for (unsigned p=0; p<8; ++p) {
        y[p].d=(id%5==0) ? 0.f : float(int(rng(state)%2049)-1024)/1024.f;
        for (unsigned i=0; i<256; ++i) y[p].qs[i]=id%3==0 ? (i&1 ? -128 : 127) : int8_t(rng(state)>>24);
        for (unsigned i=0; i<16; ++i) y[p].bsums[i]=int16_t(0x5a5a);
        const float plain=production::dev_dot_iq2_xxs_q8_K_block(&x,&y[p]);
        const float lut=production::dev_dot_iq2_xxs_q8_K_block_lut(&x,&y[p],cuda_iq2xxs_grid);
        if (bits(plain)!=bits(reference::dev_dot_iq2_xxs_q8_K_block(&x,&y[p]))) return 10;
        if (bits(lut)!=bits(reference::dev_dot_iq2_xxs_q8_K_block_lut(&x,&y[p],cuda_iq2xxs_grid))) return 11;
        // Positive scales and integral sums also give an independent scalar
        // oracle. Match each path's original floating multiplication order.
        const float xd=production::dev_f16_to_f32(x.d), d=xd*y[p].d;
        if (bits(plain)!=bits(0.125f*d*float(block_sum(x,y[p])))) return 12;
    }
    for (unsigned n=1; n<=8; ++n) {
        const cuda_block_q8_K *p[8];
        float actual[10], expected[10];
        for (unsigned i=0; i<10; ++i) actual[i]=expected[i]=float(int(i)-4)*1.25f;
        for (unsigned i=0; i<8; ++i) p[i]=i<n ? &y[i] : nullptr;
#define ARGS &x,p[0],p[1],p[2],p[3],p[4],p[5],p[6],p[7],n
        production::dev_dot_iq2_xxs_q8_K_block8_deq_lut(ARGS,actual+1,cuda_iq2xxs_grid);
        reference::dev_dot_iq2_xxs_q8_K_block8_deq_lut(ARGS,expected+1,cuda_iq2xxs_grid);
        for (unsigned i=0; i<10; ++i) if (bits(actual[i])!=bits(expected[i])) return 13;
        production::dev_dot_iq2_xxs_q8_K_block8(ARGS,actual+1);
        reference::dev_dot_iq2_xxs_q8_K_block8(ARGS,expected+1);
        for (unsigned i=0; i<10; ++i) if (bits(actual[i])!=bits(expected[i])) return 14;
#undef ARGS
        if (n<=4) {
            production::dev_dot_iq2_xxs_q8_K_block4(&x,p[0],p[1],p[2],p[3],n,actual+1);
            reference::dev_dot_iq2_xxs_q8_K_block4(&x,p[0],p[1],p[2],p[3],n,expected+1);
            for (unsigned i=0; i<10; ++i) if (bits(actual[i])!=bits(expected[i])) return 15;
        }
        for (unsigned i=0; i<10; ++i)
            if ((i==0 || i>n) && bits(actual[i])!=bits(float(int(i)-4)*1.25f)) return 16;
    }
#ifdef TEST_ROCM
    for (unsigned i=0; i<256; ++i) {
        const auto *bytes=reinterpret_cast<const unsigned char *>(&x);
        if (bits(production::iq2_xxs_dequant_256_direct(bytes,i)) !=
            bits(reference::iq2_xxs_dequant_256_direct(bytes,i))) return 17;
    }
#endif
    return 0;
}

constexpr unsigned sign_cases=128*256, block_cases=512, cases=sign_cases+block_cases;
#ifdef GPU
__global__ static void oracle(uint32_t *output) {
    unsigned i=blockIdx.x*blockDim.x+threadIdx.x;
    if (i<cases) output[i]=i<sign_cases ? signs_case(i) : block_case(i-sign_cases);
}
static void check(GPU(Error_t) error) {
    if (error!=GPU(Success)) { std::fprintf(stderr,"%s\n",GPU(GetErrorString)(error)); std::exit(1); }
}
#endif

int main(int argc,char **argv) {
    std::vector<uint32_t> output(cases+128,0xa5a5a5a5u);
#ifdef GPU
    int count=0; check(GPU(GetDeviceCount)(&count));
    const int device=argc==2 ? std::atoi(argv[1]) : 0;
    if (device<0 || device>=count) { std::fputs("visible GPU required\n",stderr); return 1; }
    check(GPU(SetDevice)(device));
    uint32_t *buffer=nullptr;
    check(GPU(Malloc)(reinterpret_cast<void **>(&buffer),output.size()*4));
    check(GPU(Memcpy)(buffer,output.data(),output.size()*4,GPU(MemcpyHostToDevice)));
    oracle<<<(cases+127)/128,128>>>(buffer+64);
    check(GPU(GetLastError)()); check(GPU(DeviceSynchronize)());
    check(GPU(Memcpy)(output.data(),buffer,output.size()*4,GPU(MemcpyDeviceToHost)));
    check(GPU(Free)(buffer));
#else
    (void)argc; (void)argv;
    for (unsigned i=0; i<cases; ++i) output[64+i]=i<sign_cases ? signs_case(i) : block_case(i-sign_cases);
#endif
    for (unsigned i=0; i<output.size(); ++i) {
        const uint32_t expected=(i<64 || i>=cases+64) ? 0xa5a5a5a5u : 0;
        if (output[i]!=expected) { std::fprintf(stderr,"FAIL case %d, check %u\n",int(i)-64,output[i]); return 1; }
    }
    std::printf("PASS: %u sign/grid pairs, signed packed DP4A; %u full blocks, 1..8 tails, null inactive pointers, guards and exact float outputs.\n",sign_cases,block_cases);
#ifndef GPU
    std::puts("Host oracle only: GPU compilation, scheduling and performance remain unverified.");
#else
    std::puts("Extracted device helpers only: full routed-kernel scheduling and performance remain unverified.");
#endif
}
