#version 460 core
layout(local_size_x = 256, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer ABlock { float a_val[]; };
layout(set = 0, binding = 1) buffer BBlock { float b_val[]; };
layout(set = 0, binding = 2) buffer OutBlock { float out_val[]; };

layout(push_constant) uniform PC {
    uint count;
} pc;

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= pc.count) return;
    out_val[gid] = a_val[gid] + b_val[gid];
}
